config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books
  get 'top' => 'books#top'
  root to: 'books#top'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

 def index
  	@books = Book.all
  	@book = Book.new
  end

  def show
  	@book = Book.find(params[:id])
  end

def create
  @book = Book.new(book_params)
  @books = Book.all
  if @book.save
  flash[:success] = "Book was successfully created."
  redirect_to @book
 else
  render :index
 end
  end

def edit
  	@book = Book.find(params[:id])
end

  def update
  @book = Book.find(params[:id])
  if @book.update(book_params)
  flash[:success] = "Book was successfully update."
 redirect_to @book

else
 render :edit
end
  end



  def destroy
  	book = Book.find(params[:id])
  	book.destroy
  	flash[:success] = "Book was successfully destroyed."
  	redirect_to books_path
  end

  private

  def book_params
  	params.require(:book).permit(:title, :body)
  end
 end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>


<%= form_with model:@book, local:true do |f| %>

 <h4>Title</h4>
	<%= f.text_field :title %>
  <h4>Body</h4>
	<%= f.text_area :body %>

  <%= f.submit 'Update Book' %>
<% end %>

<%= link_to "Show", book_path(@book) %> | <%= link_to "Back", books_path %>

app/views/books/index.html.erb
<%= flash[:success] %>

<h1>Books</h1>



<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |f| %>
    <tr>
      <td><%= f.title %></td>
      <td><%= f.body %></td>
      <td><%= link_to "show", book_path(f.id) %></td>
      <td><%= link_to "edit", edit_book_path(f.id) %></td>
      <td><%= link_to "destroy", book_path(f.id), method: :delete, data: { confirm: 'Are you sure ?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<h2>New book</h2>
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<%= form_with model:@book, local:true do |f| %>

<h4>Title</h4>
<%= f.text_field :title %>

<h4>Body</h4>
<%= f.text_field :body %>
<%= f.submit 'Create Book' %>
<% end %>

app/views/books/new.html.erb
<h2>New book</h2>
<%= form_with model:@book, local:true do |f| %>


<h4>Title</h4>
<%= f.text_field :title %>

<h4>Body</h4>
<%= f.text_field :body %>
<%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<%= flash[:success] %>

<p><strong>Title:</strong> <%= @book.title %></p>
<p><strong>Body:</strong> <%= @book.body %></p>


<%= link_to "Edit", edit_book_path(@book) %> | <%= link_to "Back", books_path %>

app/views/books/top.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
  </head>

  <body>
    <h1>ようこそ <strong>Bookers</strong>  へ！</h1>
<p><strong>Bookers</strong>  では、さまざまな書籍に関するあなたの意見や</p><p>印象を共有し交換することができます</p>
 <P>  <%= link_to "start", "/books" %></P>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>